In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
dataset=pd.read_csv('/age_height.csv')

In [ ]:
dataset

Age  Height
0    10     138
1    11     138
2    12     138
3    13     139
4    14     139
..  ...     ...
66   76     204
67   77     205
68   78     206
69   79     207
70   80     208

[71 rows x 2 columns]

In [ ]:
dataset.head()

Age  Height
0   10     138
1   11     138
2   12     138
3   13     139
4   14     139

In [ ]:
dataset.count()

Age       71
Height    71
dtype: int64

In [ ]:
dataset.describe()

Age      Height
count  71.000000   71.000000
mean   45.000000  160.873239
std    20.639767   20.842902
min    10.000000  138.000000
25%    27.500000  143.500000
50%    45.000000  155.000000
75%    62.500000  171.500000
max    80.000000  208.000000

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     71 non-null     int64
 1   Height  71 non-null     int64
dtypes: int64(2)
memory usage: 1.2 KB


In [ ]:
x=dataset.iloc[:,0:1].values

In [ ]:
print(x)

[[10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]
 [31]
 [32]
 [33]
 [34]
 [35]
 [36]
 [37]
 [38]
 [39]
 [40]
 [41]
 [42]
 [43]
 [44]
 [45]
 [46]
 [47]
 [48]
 [49]
 [50]
 [51]
 [52]
 [53]
 [54]
 [55]
 [56]
 [57]
 [58]
 [59]
 [60]
 [61]
 [62]
 [63]
 [64]
 [65]
 [66]
 [67]
 [68]
 [69]
 [70]
 [71]
 [72]
 [73]
 [74]
 [75]
 [76]
 [77]
 [78]
 [79]
 [80]]


In [ ]:
x.shape

(71, 1)

In [ ]:
x.ndim

2

In [ ]:
y=dataset.iloc[:,-1].values

In [ ]:
y

array([138, 138, 138, 139, 139, 139, 140, 140, 140, 141, 141, 141, 142,
       142, 142, 143, 143, 143, 144, 144, 145, 145, 146, 146, 147, 147,
       148, 148, 149, 149, 150, 150, 151, 152, 153, 155, 156, 157, 158,
       159, 160, 161, 162, 163, 164, 164, 165, 166, 167, 168, 169, 170,
       171, 172, 173, 175, 178, 180, 183, 185, 188, 190, 193, 195, 199,
       203, 204, 205, 206, 207, 208])

In [ ]:
y.shape

(71,)

In [ ]:
y=y.reshape(71,1)

In [ ]:
y.ndim

2

In [ ]:
print(y)

[[138]
 [138]
 [138]
 [139]
 [139]
 [139]
 [140]
 [140]
 [140]
 [141]
 [141]
 [141]
 [142]
 [142]
 [142]
 [143]
 [143]
 [143]
 [144]
 [144]
 [145]
 [145]
 [146]
 [146]
 [147]
 [147]
 [148]
 [148]
 [149]
 [149]
 [150]
 [150]
 [151]
 [152]
 [153]
 [155]
 [156]
 [157]
 [158]
 [159]
 [160]
 [161]
 [162]
 [163]
 [164]
 [164]
 [165]
 [166]
 [167]
 [168]
 [169]
 [170]
 [171]
 [172]
 [173]
 [175]
 [178]
 [180]
 [183]
 [185]
 [188]
 [190]
 [193]
 [195]
 [199]
 [203]
 [204]
 [205]
 [206]
 [207]
 [208]]


In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc_x=StandardScaler()
sc_y=StandardScaler()

In [ ]:
x=sc_x.fit_transform(x)
y=sc_y.fit_transform(y)

In [ ]:
from sklearn.svm import SVR

In [ ]:
regressor=SVR(kernel='rbf')
regressor.fit(x,y)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [ ]:
y_pred=regressor.predict(sc_x.transform([[40]]))

In [ ]:
y_pred

array([-0.44322788])

In [ ]:
y_pred = sc_y.inverse_transform(y_pred)

In [ ]:
y_pred

array([151.70037229])